apiVersion: v2
name: barbican
description: A Helm chart for barbican
type: application
version: 2.2.0
appVersion: 20.0.0-5-gd4365b8a-4-5
sources:
  - https://github.com/NeCTAR-RC/barbican-helm.git
dependencies:
- name: nectarlib
  version: 4.2.0
  repository: oci://registry.rc.nectar.org.au/nectar-helm
